version: '3'
services:
  php:
      build: ./Docker/app
      volumes:
          - .:/home/www/code
  web:
      build: ./Docker/web
      ports:
          - "80:80"
      depends_on:
          - php
